RUNFILE1 = 23
RUNFILE2 = 24
OBJECTS = g++ -o
FILE = .cpp
OPTION1 = -std=c++11 -stdlib=libc++

all:

	$(OBJECTS) $(RUNFILE1) $(RUNFILE1)$(FILE) 
	./$(RUNFILE1)
	$(OBJECTS) $(RUNFILE2) $(RUNFILE2)$(FILE)
	./$(RUNFILE2)
clean:

	rm $(RUNFILE1) $(RUNFILE2)