RUNFILE1 = figure
RUNFILE2 = virtualfunction
OBJECTS = g++ -o
FILE = .cpp


all:

	# $(OBJECTS) $(RUNFILE1) $(RUNFILE1)$(FILE)
	# ./$(RUNFILE1)
	$(OBJECTS) $(RUNFILE2) $(RUNFILE2)$(FILE) $(OPTION1)
	./$(RUNFILE2)
clean:

	rm $(RUNFILE1) $(RUNFILE2)